/**
 * Central site + SEO configuration for YARI.
 *
 * Everything SEO-related (canonical URLs, sitemap, robots, Open Graph,
 * JSON-LD structured data) reads from here so the brand, domain, contact
 * details and social profiles stay consistent across the whole app.
 *
 * The production domain can be overridden at deploy time with the
 * NEXT_PUBLIC_SITE_URL environment variable.
 */

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.yariagency.com"
).replace(/\/$/, "");

export const SITE = {
  name: "YARI",
  legalName: "YARI Labs",
  /** One-liner used as the default meta description / tagline. */
  tagline:
    "Dubai-based e-commerce, software and logistics studio — we design, build and ship the whole stack for ambitious brands.",
  /** Geographic focus for local SEO. */
  areaServed: ["Dubai", "United Arab Emirates", "GCC", "United Kingdom"],
  locality: "Dubai",
  region: "Dubai",
  country: "AE",
  email: "contact@yari.com",
  phones: [
    { label: "UAE", number: "+971 50 863 2422", e164: "+971508632422" },
    { label: "UK", number: "+44 7466 368427", e164: "+447466368427" },
  ],
  /** 1200×630 social share image (generated by app/opengraph-image.tsx). */
  ogImage: "/opengraph-image",
  logo: "/yari-logo.png",
  social: {
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    x: "https://x.com",
    github: "https://github.com",
  },
} as const;

/** Absolute URL helper — pass a root-relative path, get a canonical URL back. */
export function absoluteUrl(path = "/"): string {
  if (!path.startsWith("/")) path = `/${path}`;
  return `${SITE_URL}${path}`;
}

/** Default keyword set woven through the Dubai-focused metadata. */
export const PRIMARY_KEYWORDS = [
  "e-commerce development Dubai",
  "ecommerce website development Dubai",
  "Shopify development Dubai",
  "e-commerce agency Dubai",
  "order fulfilment Dubai",
  "3PL Dubai",
  "Odoo integration Dubai",
  "Zoho integration UAE",
  "logistics company Dubai",
  "web development UAE",
];
